name: SurvivalPlus
main: veth.vetheon.survival.Survival
authors: [FattyMieo, ShaneBee, VetheonGames, Pixelated Studios]
version: '${project.version}'
api-version: '1.18'
softdepend:
   - PlaceholderAPI
   - Multiverse-Core
commands:
   reload-survival:
      aliases: [survival-reload]
      description: Reload configurations
      usage: /<command>
      permission: survivalplus.reload
   recipes:
      description: Unused
      usage: /<command>
   togglechat:
      description: Toggling between Global and Local Chat
      usage: /<command> [global|local]
      aliases: [tc]
      permission: survivalplus.togglechat
   status:
      description: Checking Hunger and Thirst Status
      usage: /<command>
      aliases: [stat, s]
   snowgen:
      description: Regenerates snow layers for all chunks, or toggles real-time snow formation
      usage: /<command> [on|off]
      permission: survivalplus.snowgen
   giveitem:
      description: Give a SurvivalPlus item to a player
      usage: /<command> <player> <item>
      permission: survivalplus.giveitem
      aliases: [survivalitem, itemgive]
   nutrition:
      description: Open the nutrition GUI
      usage: /<command>
      permission: survivalplus.nutrition.gui
   heal:
      description: Heal a player
      usage: /<command> [player]
      permission: survivalplus.heal
   playerdata:
      description: Adjust player data
      usage: /<command> (player) (add/remove/set) (stat) (amount)
      permission: survivalplus.playerdata
