name: Feature Request
description: Suggest a new Feature

name: Feature Suggestion
description: Suggest an feature for Minehut
labels: ["feature request"]

body:
  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Confirm all of these are checked and valid.
      options:
        - label: I am NOT reporting a security vulnerability
          required: true
        - label: I have searched the Issue Tracker to make sure this is not a duplicate issue
          required: true
        - label: This issue does not contain any sensitive information
          required: true
  - type: textarea
    id: idea
    attributes:
      label: What is the feature you are requesting?
      description: Your feature suggestion should include a clear concise description of the feature.
    validations:
      required: true
  - type: textarea
    id: howuse
    attributes:
      label: How is this feature useful?
      description: Who does the feature benefit? How is it useful to people?
    validations:
      required: true
  - type: textarea
    id: howdo
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true
  - type: textarea
    id: moreinfo
    attributes:
      label: Additional Information
      description: Any additional information / context?
